permalink: /:year/:month/:day/:title.html
paginate: 10
markdown: redcarpet

# 作者信息
author: 
  name: 阿牛
  email: mail_aniu@126.com
  link: http://aniux.com
  weibo: http://weibo.com/277021163
  github: http://github.com/aniux
  
# 站点信息
title: 阿牛的博客 
description: 阿牛的博客
url: http://aniux.com
rss_url: /pages/atom.xml

# gavatar头像及Favicon
gavatar: http://tp1.sinaimg.cn/2099947432/180/40001519758/1
favicon: http://www.sudu.cn/ico/favicon.ico

# google analytics 设置
ga:
  id: UA-55185080-1
  url: aniux.com

# disqus 设置
disqus:
  shortname: 

# 主题设置，自动激活某个标签
active: 笔记

# 首页除了最新文章外显示分类
cates: 
  - 笔记

# 中文本地化
locals:
  tags: 标签
  about: 关于
  newest: 最新文章
  archive: 归档
  content: 目录
